[package]
name = "tobychat"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
<<<<<<< HEAD
surrealdb = "1.5.3"
=======
sqlx = "0.7.4"
>>>>>>> f29454a42c91a67900bd4df20f8a6079dc64c947
