[package]
name = "tobychat"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["secrets"] }
rocket_dyn_templates = {version = "0.2.0", features = ["handlebars"]}
serde = "1.0.203"
surrealdb = "1.5.3"

[profile.dev]
debug = 0
strip = "debuginfo"
